# Generated by Django 4.1.2 on 2022-10-14 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_princ', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('sinopse', models.TextField(max_length=500)),
                ('atores', models.CharField(max_length=100)),
                ('direcao', models.CharField(max_length=100)),
                ('trilha_sonora', models.CharField(max_length=100)),
                ('confeccao', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=30)),
                ('classificacao', models.CharField(max_length=30)),
                ('agradecimentos', models.TextField(max_length=500)),
                ('is_espetaculo', models.BooleanField()),
                ('link', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='fotos/%d/%m/%Y/')),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.FileField(upload_to='files/%d/%m/%Y')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.atividades')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.BooleanField()),
                ('premio', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.atividades')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=10, verbose_name='Duração')),
                ('idade', models.CharField(max_length=20)),
                ('dataFinal', models.DateField()),
                ('dataInicial', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('dataInserido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.atividades')),
            ],
        ),
    ]
