# Generated by Django 4.1.2 on 2022-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0002_remove_atividades_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='agradecimentos',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
