# Generated by Django 4.1.2 on 2022-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0003_alter_atividades_agradecimentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='is_espetaculo',
        ),
        migrations.AddField(
            model_name='atividades',
            name='tipo',
            field=models.CharField(choices=[('ESPETACULO', 'Espetáculo'), ('OFICINA', 'Oficina')], default='ESPETACULO', max_length=20),
            preserve_default=False,
        ),
    ]
