# Generated by Django 4.1.2 on 2022-10-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0006_alter_atividades_classificacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atividades',
            new_name='Atividade',
        ),
    ]
