# Generated by Django 4.1.2 on 2022-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0008_alter_agenda_espetaculo_alter_agenda_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='inscricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link para inscrição, se houver'),
        ),
    ]
