# Generated by Django 4.1.2 on 2022-10-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0009_agenda_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='espetaculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.atividade'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='premio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prêmio'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Currículo'), (2, 'Premio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='evento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.evento'),
        ),
    ]
