# Generated by Django 4.1.2 on 2022-10-14 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0010_evento_alter_curriculo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='dataInserido',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
