# Generated by Django 4.1.2 on 2022-10-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0011_evento_ativo_evento_datainserido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('atores', models.CharField(max_length=100)),
                ('direcao', models.CharField(max_length=100)),
                ('trilha_sonora', models.CharField(blank=True, max_length=100)),
                ('confeccao', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=30)),
                ('classificacao', models.CharField(choices=[('0', 'Livre'), ('10', 'Recomendado para maiores de 10 anos'), ('12', 'Recomendado para maiores de 12 anos'), ('14', 'Recomendado para maiores de 14 anos'), ('16', 'Recomendado para maiores de 16 anos'), ('18', 'Recomendado para maiores de 18 anos')], max_length=40)),
                ('agradecimentos', models.TextField(blank=True)),
                ('foto_principal', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='dataFinal',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='dataInicial',
            new_name='data_inicial',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='dataInserido',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='dataInserido',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dataInserido',
        ),
        migrations.RemoveField(
            model_name='fotos',
            name='dataInserido',
        ),
        migrations.RemoveField(
            model_name='integrantes',
            name='dataInserido',
        ),
        migrations.RemoveField(
            model_name='textos',
            name='dataInserido',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='espetaculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.espetaculo'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='espetaculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.espetaculo'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='espetaculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.espetaculo'),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
