# Generated by Django 4.1.2 on 2022-10-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0012_espetaculo_rename_datafinal_agenda_data_final_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Textos',
        ),
    ]
