# Generated by Django 4.1.2 on 2022-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0013_delete_textos'),
    ]

    operations = [
        migrations.AddField(
            model_name='espetaculo',
            name='video',
            field=models.CharField(default='', max_length=200, verbose_name='Vídeo (link do youtube)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='classificacao',
            field=models.CharField(choices=[('0', 'Livre'), ('10', 'Recomendado para maiores de 10 anos'), ('12', 'Recomendado para maiores de 12 anos'), ('14', 'Recomendado para maiores de 14 anos'), ('16', 'Recomendado para maiores de 16 anos'), ('18', 'Recomendado para maiores de 18 anos')], max_length=40, verbose_name='Classificação indicatica'),
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='confeccao',
            field=models.CharField(max_length=100, verbose_name='Confecção'),
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='direcao',
            field=models.CharField(max_length=100, verbose_name='Direção'),
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='duracao',
            field=models.CharField(max_length=30, verbose_name='Duração'),
        ),
    ]
