# Generated by Django 4.1.2 on 2022-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0015_alter_espetaculo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
