# Generated by Django 4.1.2 on 2022-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0016_alter_integrantes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='descricao',
            field=models.TextField(),
        ),
    ]
