# Generated by Django 4.1.2 on 2022-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0021_alter_agenda_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
