# Generated by Django 4.1.2 on 2022-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0023_cursos_programacurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('resumo', models.CharField(blank=True, max_length=200, null=True)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
