# Generated by Django 4.1.2 on 2022-10-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0024_textos'),
    ]

    operations = [
        migrations.AddField(
            model_name='textos',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='teatrodidatico.cursos'),
            preserve_default=False,
        ),
    ]
