# Generated by Django 4.1.2 on 2022-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0025_textos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programacurso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
