# Generated by Django 4.1.2 on 2022-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0026_cursos_ativo_programacurso_ativo_textos_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='programacao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
