# Generated by Django 4.1.2 on 2022-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0027_cursos_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='foto_principal',
            field=models.ImageField(default='', upload_to='fotos/%d/%m/%Y/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textos',
            name='arquivo',
            field=models.FileField(upload_to='files/%d/%m/%Y/'),
        ),
    ]
