# Generated by Django 4.1.2 on 2022-10-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0028_cursos_foto_principal_alter_textos_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatrodidatico.cursos'),
        ),
        migrations.AlterField(
            model_name='textos',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatrodidatico.cursos'),
        ),
    ]
