# Generated by Django 4.1.2 on 2022-10-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0030_alter_cursos_modalidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='data_inscriaco_inicial',
            new_name='data_inscricao_inicial',
        ),
    ]
