# Generated by Django 4.1.2 on 2022-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatrodidatico', '0031_rename_data_inscriaco_inicial_cursos_data_inscricao_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='resumo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
